create database customer_behaviour;
--
select*from customer_behaviour;
 
    ALTER TABLE customer_behaviour
RENAME COLUMN `purchase_amount_usd` TO purchase_amount;

-- Business Insights Questions
----------------------------------------------------------------------------------------------------------------------------

-- 1. Which category generates highest revenue?
SELECT 
	category,
	ROUND(SUM(purchase_amount),2) AS highest_revenue
FROM customer_behaviour
GROUP BY category
ORDER BY highest_revenue DESC;

-- 2. Are discounts actually increasing purchase value?

SELECT 
    discount_applied,
    COUNT(*) AS total_orders,
    ROUND(AVG(`purchase_amount`), 2) AS avg_purchase,
    ROUND(SUM(`purchase_amount`), 2) AS total_revenue
FROM customer_behaviour
GROUP BY discount_applied;

-- 3. What is the total revenue generated by male and female customer ? 
select
     gender,
     sum(purchase_amount) as total_revenue
from customer_behaviour
group by gender
order by total_revenue desc ;

-- 4. Which customer used a discount but still spent more then the average purchase amount ?
SELECT 
    customer_id,
    `purchase_amount`
FROM customer_behaviour
WHERE discount_applied = 'Yes'
AND `purchase_amount` > (
    SELECT AVG(`purchase_amount`)
    FROM customer_behaviour
order by purchase_amount desc
);

-- 5. Which are the top/bottom 5 products with the highest average review rating. 
SELECT 
    item_purchased,
    ROUND(AVG(review_rating), 2) AS avg_ratings
FROM customer_behaviour
GROUP BY item_purchased
ORDER BY avg_ratings DESC
LIMIT 5;

-- 6. Average purchase: Standard vs Express shipping
SELECT 
    shipping_type,
    ROUND(AVG(`purchase_amount`), 2) AS avg_purchase
    FROM customer_behaviour
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;


-- 7. Do subscribed customers spend more ? Compare average speed and total revenue between subscribers and non-subscribers.
SELECT 
    subscription_status,
    COUNT(*) AS total_orders,
    ROUND(AVG(`purchase_amount`), 2) AS avg_purchase,
    ROUND(SUM(`purchase_amount`), 2) AS total_revenue
FROM customer_behaviour
GROUP BY subscription_status;

-- 8. Top 5 products with highest discount usage %
SELECT 
    item_purchased,
    COUNT(CASE WHEN discount_applied = 'Yes' THEN 1 END) * 100.0 / COUNT(*) AS discount_usage_pct
FROM customer_behaviour
GROUP BY item_purchased
ORDER BY discount_usage_pct DESC
LIMIT 5;


-- 9. Segment customer into new, returning and loyal based on their total number of previous purchase, 
-- and show the count of each segment.

SELECT 
    CASE 
        WHEN previous_purchases = 0 THEN 'New'
        WHEN previous_purchases BETWEEN 1 AND 5 THEN 'Returning'
        ELSE 'Loyal'
    END AS customer_segment,
    COUNT(*) AS customer_count
FROM customer_behaviour
GROUP BY customer_segment;

-- 10. What are the top 3 most purchased products within each category ?
WITH product_counts AS (
    SELECT 
        category,
        item_purchased,
        COUNT(*) AS purchase_count,
        RANK() OVER (PARTITION BY category ORDER BY COUNT(*) DESC) AS rnk
    FROM customer_behaviour
    GROUP BY category, item_purchased
)
SELECT 
    category,
    item_purchased,
    purchase_count
FROM product_counts
WHERE rnk <= 3;


-- 11. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe ?
SELECT 
    subscription_status,
    COUNT(*) AS total_customers
FROM customer_behaviour
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- 12. What is the revenue contribution of each age group ? 
SELECT 
    CASE 
        WHEN age < 20 THEN 'Teen'
        WHEN age BETWEEN 20 AND 35 THEN 'Young Adult'
        WHEN age BETWEEN 36 AND 50 THEN 'Adult'
        ELSE 'Senior'
    END AS age_group,
    ROUND(SUM(`purchase_amount`), 2) AS total_revenue
FROM customer_behaviour
GROUP BY age_group
ORDER BY total_revenue DESC;